added validation stack if exist

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -60,11 +60,22 @@ jobs:
       - name: Deploy ECS stack
         if: steps.compare-hashes.outputs.stdout == ''
         run: |
-          # El objeto no existe o el archivo ha cambiado, realiza la creación de la pila de CloudFormation aquí
+          # Intenta crear la pila de CloudFormation, maneja la excepción si ya existe
+          set +e
           aws cloudformation create-stack \
             --stack-name dockeep-clients-ms-ecs-stack \
             --template-url https://${{ env.S3_BUCKET_NAME }}.s3.${{ env.AWS_REGION }}.amazonaws.com/${{ env.OBJECT_KEY }} \
             --capabilities CAPABILITY_NAMED_IAM
+          create_stack_exit_code=$?
+          set -e
+
+          if [ $create_stack_exit_code -eq 254 ]; then
+            # El stack ya existe, puedes manejarlo aquí
+            echo "Stack already exists. Continuing..."
+          elif [ $create_stack_exit_code -ne 0 ]; then
+            echo "Failed to create CloudFormation stack."
+            exit 1
+          fi
 
       - name: Wait for stack creation
         run: |
