latest

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -62,19 +62,20 @@ jobs:
         run: |
           # Intenta crear la pila de CloudFormation, maneja la excepción si ya existe
           set +e
-          aws cloudformation create-stack \
+          create_stack_output=$(aws cloudformation create-stack \
             --stack-name dockeep-clients-ms-ecs-stack \
             --template-url https://${{ env.S3_BUCKET_NAME }}.s3.${{ env.AWS_REGION }}.amazonaws.com/${{ env.OBJECT_KEY }} \
-            --capabilities CAPABILITY_NAMED_IAM
+            --capabilities CAPABILITY_NAMED_IAM 2>&1)
           create_stack_exit_code=$?
           set -e
 
-          if [ $create_stack_exit_code -eq 255 ]; then
-            # El stack ya existe, puedes manejarlo aquí
-            echo "Stack already exists. Continuing..."
-          elif [ $create_stack_exit_code -ne 0 ]; then
-            echo "Failed to create CloudFormation stack."
-            exit 1
+          if [ $create_stack_exit_code -ne 0 ]; then
+            if [[ $create_stack_output == *"AlreadyExistsException"* ]]; then
+              echo "Stack already exists. Continuing..."
+            else
+              echo "Failed to create CloudFormation stack."
+              exit 1
+            fi
           fi
 
       - name: Wait for stack creation
